import React from "react";


function GetCountries() {

    const countryArr = ["USA",
    "Italy",
    "Spain",
    "Germany",
    "France",
    "Iran",
    "UK",
    "Switzerland",
    "Turkey",
    "Belgium",
    "Netherlands",
    "Canada",
    "Austria",
    "S. Korea",
    "Portugal",
    "Brazil",
    "Israel",
    "Sweden",
    "Australia",
    "Norway",
    "Czechia",
    "Ireland",
    "Russia",
    "Chile",
    "Denmark",
    "Ecuador",
    "Malaysia",
    "Poland",
    "Romania",
    "Philippines",
    "Japan",
    "India",
    "Luxembourg",
    "Pakistan",
    "Thailand",
    "Saudi Arabia",
    "Indonesia",
    "Greece",
    "Finland",
    "Mexico",
    "Panama",
    "South Africa",
    "Peru",
    "Dominican Republic",
    "Iceland",
    "Argentina",
    "Serbia",
    "Colombia",
    "Singapore",
    "UAE",
    "Croatia",
    "Algeria",
    "Qatar",
    "Ukraine",
    "Slovenia",
    "New Zealand",
    "Egypt",
    "Estonia",
    "Hong Kong",
    "Iraq",
    "Diamond Princess",
    "Morocco",
    "Lithuania",
    "Armenia",
    "Bahrain",
    "Hungary",
    "Bosnia and Herzegovina",
    "Moldova",
    "Lebanon",
    "Bulgaria",
    "Latvia",
    "Tunisia",
    "Kazakhstan",
    "Andorra",
    "Slovakia",
    "Azerbaijan",
    "Costa Rica",
    "North Macedonia",
    "Uruguay",
    "Cyprus",
    "Kuwait",
    "Taiwan",
    "Réunion",
    "Cameroon",
    "Belarus",
    "Jordan",
    "Burkina Faso",
    "Albania",
    "Afghanistan",
    "San Marino",
    "Cuba",
    "Vietnam",
    "Oman",
    "Honduras",
    "Uzbekistan",
    "Ghana",
    "Malta",
    "Senegal",
    "Ivory Coast",
    "Channel Islands",
    "Nigeria",
    "Faeroe Islands",
    "Mauritius",
    "Palestine",
    "Sri Lanka",
    "Venezuela",
    "Montenegro",
    "Martinique",
    "DRC",
    "Georgia",
    "Brunei",
    "Bolivia",
    "Kyrgyzstan",
    "Guadeloupe",
    "Mayotte",
    "Cambodia",
    "Kenya",
    "Niger",
    "Trinidad and Tobago",
    "Isle of Man",
    "Paraguay",
    "Gibraltar",
    "Rwanda",
    "Liechtenstein",
    "Monaco",
    "Aruba",
    "Madagascar",
    "Bangladesh",
    "Guinea",
    "French Guiana",
    "Jamaica",
    "Guatemala",
    "El Salvador",
    "Barbados",
    "Uganda",
    "Macao",
    "Djibouti",
    "Togo",
    "Zambia",
    "French Polynesia",
    "Mali",
    "Bermuda",
    "Ethiopia",
    "Cayman Islands",
    "Bahamas",
    "Congo",
    "Saint Martin",
    "Eritrea",
    "Gabon",
    "Myanmar",
    "Tanzania",
    "Guyana",
    "Maldives",
    "Sint Maarten",
    "Haiti",
    "New Caledonia",
    "Syria",
    "Equatorial Guinea",
    "Mongolia",
    "Namibia",
    "Benin",
    "Saint Lucia",
    "Dominica",
    "Curaçao",
    "Libya",
    "Greenland",
    "Grenada",
    "Laos",
    "Mozambique",
    "Seychelles",
    "Suriname",
    "MS Zaandam",
    "Zimbabwe",
    "Antigua and Barbuda",
    "Guinea-Bissau",
    "Saint Kitts and Nevis",
    "Eswatini",
    "Angola",
    "Sudan",
    "CAR",
    "Chad",
    "Fiji",
    "Vatican City",
    "Cabo Verde",
    "Mauritania",
    "Nepal",
    "Liberia",
    "St. Barth",
    "Nicaragua",
    "Bhutan",
    "Montserrat",
    "Somalia",
    "Turks and Caicos",
    "Botswana",
    "Gambia",
    "Anguilla",
    "Belize",
    "British Virgin Islands",
    "Burundi",
    "Malawi",
    "Caribbean Netherlands",
    "St. Vincent Grenadines",
    "Sierra Leone",
    "Papua New Guinea",
    "Timor-Leste",
    "China"]

    return countryArr;

        

    
}


// API key 0d7e71ff7ddd480b83368a04bb626671

export default GetCountries;