function GetCountries() {
  const countryArr = [
    { key: "0", text: "USA" },
    { key: "1", text: "Italy" },
    { key: "2", text: "Spain" },
    { key: "3", text: "Germany" },
    { key: "4", text: "France" },
    { key: "5", text: "Iran" },
    { key: "6", text: "UK" },
    { key: "7", text: "Switzerland" },
    { key: "8", text: "Turkey" },
    { key: "9", text: "Belgium" },
    { key: "10", text: "Netherlands" },
    { key: "11", text: "Canada" },
    { key: "12", text: "Austria" },
    { key: "13", text: "S. Korea" },
    { key: "14", text: "Portugal" },
    { key: "15", text: "Brazil" },
    { key: "16", text: "Israel" },
    { key: "17", text: "Sweden" },
    { key: "18", text: "Australia" },
    { key: "19", text: "Norway" },
    { key: "20", text: "Czechia" },
    { key: "21", text: "Ireland" },
    { key: "22", text: "Russia" },
    { key: "23", text: "Chile" },
    { key: "24", text: "Denmark" },
    { key: "25", text: "Ecuador" },
    { key: "26", text: "Malaysia" },
    { key: "27", text: "Poland" },
    { key: "28", text: "Romania" },
    { key: "29", text: "Philippines" },
    { key: "30", text: "Japan" },
    { key: "31", text: "India" },
    { key: "32", text: "Luxembourg" },
    { key: "33", text: "Pakistan" },
    { key: "34", text: "Thailand" },
    { key: "35", text: "Saudi Arabia" },
    { key: "36", text: "Indonesia" },
    { key: "37", text: "Greece" },
    { key: "38", text: "Finland" },
    { key: "39", text: "Mexico" },
    { key: "40", text: "Panama" },
    { key: "41", text: "South Africa" },
    { key: "42", text: "Peru" },
    { key: "43", text: "Dominican Republic" },
    { key: "44", text: "Iceland" },
    { key: "45", text: "Argentina" },
    { key: "46", text: "Serbia" },
    { key: "47", text: "Colombia" },
    { key: "48", text: "Singapore" },
    { key: "49", text: "UAE" },
    { key: "50", text: "Croatia" },
    { key: "51", text: "Algeria" },
    { key: "52", text: "Qatar" },
    { key: "53", text: "Ukraine" },
    { key: "54", text: "Slovenia" },
    { key: "55", text: "New Zealand" },
    { key: "56", text: "Egypt" },
    { key: "57", text: "Estonia" },
    { key: "58", text: "Hong Kong" },
    { key: "59", text: "Iraq" },
    { key: "60", text: "Diamond Princess" },
    { key: "61", text: "Morocco" },
    { key: "62", text: "Lithuania" },
    { key: "63", text: "Armenia" },
    { key: "64", text: "Bahrain" },
    { key: "65", text: "Hungary" },
    { key: "66", text: "Bosnia and Herzegovina" },
    { key: "67", text: "Moldova" },
    { key: "68", text: "Lebanon" },
    { key: "69", text: "Bulgaria" },
    { key: "70", text: "Latvia" },
    { key: "71", text: "Tunisia" },
    { key: "72", text: "Kazakhstan" },
    { key: "73", text: "Andorra" },
    { key: "74", text: "Slovakia" },
    { key: "75", text: "Azerbaijan" },
    { key: "76", text: "Costa Rica" },
    { key: "77", text: "North Macedonia" },
    { key: "78", text: "Uruguay" },
    { key: "79", text: "Cyprus" },
    { key: "80", text: "Kuwait" },
    { key: "81", text: "Taiwan" },
    { key: "82", text: "Réunion" },
    { key: "83", text: "Cameroon" },
    { key: "84", text: "Belarus" },
    { key: "85", text: "Jordan" },
    { key: "86", text: "Burkina Faso" },
    { key: "87", text: "Albania" },
    { key: "88", text: "Afghanistan" },
    { key: "89", text: "San Marino" },
    { key: "90", text: "Cuba" },
    { key: "91", text: "Vietnam" },
    { key: "92", text: "Oman" },
    { key: "93", text: "Honduras" },
    { key: "94", text: "Uzbekistan" },
    { key: "95", text: "Ghana" },
    { key: "96", text: "Malta" },
    { key: "97", text: "Senegal" },
    { key: "98", text: "Ivory Coast" },
    { key: "99", text: "Channel Islands" },
    { key: "100", text: "Nigeria" },
    { key: "101", text: "Faeroe Islands" },
    { key: "102", text: "Mauritius" },
    { key: "103", text: "Palestine" },
    { key: "104", text: "Sri Lanka" },
    { key: "105", text: "Venezuela" },
    { key: "106", text: "Montenegro" },
    { key: "107", text: "Martinique" },
    { key: "108", text: "DRC" },
    { key: "109", text: "Georgia" },
    { key: "110", text: "Brunei" },
    { key: "111", text: "Bolivia" },
    { key: "112", text: "Kyrgyzstan" },
    { key: "113", text: "Guadeloupe" },
    { key: "114", text: "Mayotte" },
    { key: "115", text: "Cambodia" },
    { key: "116", text: "Kenya" },
    { key: "117", text: "Niger" },
    { key: "118", text: "Trinidad and Tobago" },
    { key: "119", text: "Isle of Man" },
    { key: "120", text: "Paraguay" },
    { key: "121", text: "Gibraltar" },
    { key: "122", text: "Rwanda" },
    { key: "123", text: "Liechtenstein" },
    { key: "124", text: "Monaco" },
    { key: "125", text: "Aruba" },
    { key: "126", text: "Madagascar" },
    { key: "127", text: "Bangladesh" },
    { key: "128", text: "Guinea" },
    { key: "129", text: "French Guiana" },
    { key: "130", text: "Jamaica" },
    { key: "131", text: "Guatemala" },
    { key: "132", text: "El Salvador" },
    { key: "133", text: "Barbados" },
    { key: "134", text: "Uganda" },
    { key: "135", text: "Macao" },
    { key: "136", text: "Djibouti" },
    { key: "137", text: "Togo" },
    { key: "138", text: "Zambia" },
    { key: "139", text: "French Polynesia" },
    { key: "140", text: "Mali" },
    { key: "141", text: "Bermuda" },
    { key: "142", text: "Ethiopia" },
    { key: "143", text: "Cayman Islands" },
    { key: "144", text: "Bahamas" },
    { key: "145", text: "Congo" },
    { key: "146", text: "Saint Martin" },
    { key: "147", text: "Eritrea" },
    { key: "148", text: "Gabon" },
    { key: "149", text: "Myanmar" },
    { key: "150", text: "Tanzania" },
    { key: "151", text: "Guyana" },
    { key: "152", text: "Maldives" },
    { key: "153", text: "Sint Maarten" },
    { key: "154", text: "Haiti" },
    { key: "155", text: "New Caledonia" },
    { key: "156", text: "Syria" },
    { key: "157", text: "Equatorial Guinea" },
    { key: "158", text: "Mongolia" },
    { key: "159", text: "Namibia" },
    { key: "160", text: "Benin" },
    { key: "161", text: "Saint Lucia" },
    { key: "162", text: "Dominica" },
    { key: "163", text: "Curaçao" },
    { key: "164", text: "Libya" },
    { key: "165", text: "Greenland" },
    { key: "166", text: "Grenada" },
    { key: "167", text: "Laos" },
    { key: "168", text: "Mozambique" },
    { key: "169", text: "Seychelles" },
    { key: "170", text: "Suriname" },
    { key: "171", text: "MS Zaandam" },
    { key: "172", text: "Zimbabwe" },
    { key: "173", text: "Antigua and Barbuda" },
    { key: "174", text: "Guinea-Bissau" },
    { key: "175", text: "Saint Kitts and Nevis" },
    { key: "176", text: "Eswatini" },
    { key: "177", text: "Angola" },
    { key: "178", text: "Sudan" },
    { key: "179", text: "CAR" },
    { key: "180", text: "Chad" },
    { key: "181", text: "Fiji" },
    { key: "182", text: "Vatican City" },
    { key: "183", text: "Cabo Verde" },
    { key: "184", text: "Mauritania" },
    { key: "185", text: "Nepal" },
    { key: "186", text: "Liberia" },
    { key: "187", text: "St. Barth" },
    { key: "188", text: "Nicaragua" },
    { key: "189", text: "Bhutan" },
    { key: "190", text: "Montserrat" },
    { key: "191", text: "Somalia" },
    { key: "192", text: "Turks and Caicos" },
    { key: "193", text: "Botswana" },
    { key: "194", text: "Gambia" },
    { key: "195", text: "Anguilla" },
    { key: "196", text: "Belize" },
    { key: "197", text: "British Virgin Islands" },
    { key: "198", text: "Burundi" },
    { key: "199", text: "Malawi" },
    { key: "200", text: "Caribbean Netherlands" },
    { key: "201", text: "St. Vincent Grenadines" },
    { key: "202", text: "Sierra Leone" },
    { key: "203", text: "Papua New Guinea" },
    { key: "204", text: "Timor-Leste" },
    { key: "205", text: "China" },
  ];

  return countryArr;
}

// API key 0d7e71ff7ddd480b83368a04bb626671

export default GetCountries;
